### ISSUE TITLE
Add More Information To The Buffer Name

### ISSUE THREAD

**Issue by lethc** [EL-MASTOR/bufferlist.nvim#5]
I like your plugin. However, I've noticed that I usually open files with the same name in different directories and as you can see I got confused about which file I want to edit when I use your plugin, so I'd like you to consider add an option to show the path of the buffers. Thanks for your plugin by the way, it's really beautiful 👍️

**Comment by EL-MASTOR** [comment]
> I like your plugin. However, I've noticed that I usually open files with the same name in different directories and as you can see I got confused about which file I want to edit when I use your plugin, so I'd like you to consider add an option to show the path of the buffers. Thanks for your plugin by the way, it's really beautiful 👍️

Hi, thank you so much for taking time to suggest new features for the plugin. I really appreciate it.
Yes, I will add the ability to toggle between the way the buffer names are shown, one of them being the output of the commend `:f`. Which is the relative path to either the neovim cwd, or the home directory mostly. Which one to show first will also be configurable. This feature and more will be available in the next update in the next few days.
Thank you again a lot for your suggestion. If you have any other awesome ideas, please let me know, I appreciate every suggestion.

**Comment by oalders** [comment]
Thanks for sharing your work. I wanted to 👍🏻 this suggestion. This is what I'm currently seeing and it's so confusing. 😅 

<img width="370" alt="Bildschirmfoto 2024-10-22 um 3 55 42 PM" src="https://github.com/user-attachments/assets/5e747b8d-4242-4d32-bb3b-f996968dd936">

**Comment by EL-MASTOR** [comment]
> I like your plugin. However, I've noticed that I usually open files with the same name in different directories and as you can see I got confused about which file I want to edit when I use your plugin, so I'd like you to consider add an option to show the path of the buffers. Thanks for your plugin by the way, it's really beautiful 👍️

Bufferlist.nvim has been updated. You can now  toggle the relative path with `toggle_path` keymap, and show path first with `show_path` option. The update also introduces custom keymaps options, you can now add your own keymaps to the the BufferList and customize it to your liking. Check out the readme for more
