### ISSUE TITLE
Bufferlist crashes when attempting to close window with one buffer open

### ISSUE THREAD

**Issue by BBFifield** [EL-MASTOR/bufferlist.nvim#7]
I'm receiving the following error when I only have one buffer open and trying to quit the bufferlist window.

```
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2()..WinLeave Autocommands for "<buffer=68>": Vim(bwipeout):E36: Not enough room
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...local/share/nvim/lazy/bufferlist.nvim/lua/bufferlist.lua:390: in function <...local/share/nvim/lazy/bufferlist.nvim/lua/bufferlist.lua:389>
```

This is via alacritty on linux.

**Comment by EL-MASTOR** [comment]
Hi.
I am sorry about the too late response.
these informations don't help me to reproduce the bug.
I need more info to see if I can reproduce it

**Comment by BBFifield** [comment]
Hi, 

After carefully trimming down my neovim config, I've found that the issue seems to only occur when you have a component added to the winbar section of lualine. 

Here is the minimal lualine config I used to reproduce the error:

```
return {
	"nvim-lualine/lualine.nvim",
	dependencies = {
		"nvim-tree/nvim-web-devicons",
	},
	opts = {
		winbar = {
			lualine_z = {
				{
					"filename",
				},
			},
		},
	},
}
```

**Comment by EL-MASTOR** [comment]
Hi,
That was helpful, I have removed the not so necessary WinLeave command, and got it fixed. It should work fine at your end now.
Thank you for helping me improve bufferlist. If you have got any suggestion or issue, you can always tell me, I appreciate every help.
Have a good day.
